plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
}

android {
    namespace 'com.fluffycat.sensorsmanager'
    compileSdk 34

    defaultConfig {
        applicationId "com.fluffycat.sensorsmanager"
        minSdk 21
        targetSdk 34
        versionCode 2
        versionName "1.0.0"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    lint {
        abortOnError false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            resValue "string", "adMainBannerViewAdUnitId", "ca-app-pub-7809340407306359/8044658435"
            buildConfigField "String", "SERVER_URL", "\"http://192.168.0.108:8080/\""
        }
        debug {
            resValue "string", "adMainBannerViewAdUnitId", "ca-app-pub-3940256099942544/6300978111"
            buildConfigField "String", "SERVER_URL", "\"http://192.168.0.108:8080/\""
        }
    }

    testOptions {
        unitTests {
            returnDefaultValues = true
            all {
                useJUnitPlatform()
            }
        }
    }
}

dependencies {
    implementation project(':shared')

    implementation libs.mpandroidchart
    implementation libs.kotlin.reflect

    implementation libs.coroutines.core
    implementation libs.coroutines.android

    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.fragment.ktx
    implementation libs.androidx.lifecycle.service
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.navigation.fragment.ktx
    implementation libs.androidx.navigation.ui.ktx
    implementation libs.material

    implementation libs.koin.android

    implementation libs.retrofit
    implementation libs.retrofit.converter.jackson

    implementation libs.flurry.analytics
    implementation libs.play.services.ads

    testImplementation libs.junit.jupiter.api
    testImplementation libs.junit.jupiter.params
    testRuntimeOnly libs.junit.jupiter.engine
    testImplementation libs.mockito.kotlin
    testImplementation libs.mockito.inline
    testImplementation libs.mockito.core

    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.espresso.core
}
