package com.fluffycat.sensorsmanager.sensors

import android.hardware.Sensor
import android.os.Build

const val ACCELEROMETER_SENSOR_TYPE = Sensor.TYPE_ACCELEROMETER
const val GYROSCOPE_SENSOR_TYPE = Sensor.TYPE_GYROSCOPE
const val LIGHT_SENSOR_TYPE = Sensor.TYPE_LIGHT
const val LINEAR_ACCELERATION_SENSOR_TYPE = Sensor.TYPE_LINEAR_ACCELERATION
const val MAGNETIC_FIELD_SENSOR_TYPE = Sensor.TYPE_MAGNETIC_FIELD
const val PROXIMITY_SENSOR_TYPE = Sensor.TYPE_PROXIMITY
const val ROTATION_VECTOR_SENSOR_TYPE = Sensor.TYPE_ROTATION_VECTOR
val HEART_RATE_SENSOR_TYPE = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT_WATCH) {
    Sensor.TYPE_HEART_RATE
} else {
    -1
}

class SensorValueProvider {
    fun getExistingSensors() =
        listOf(ACCELEROMETER_SENSOR_TYPE, GYROSCOPE_SENSOR_TYPE, LIGHT_SENSOR_TYPE, LINEAR_ACCELERATION_SENSOR_TYPE,
                MAGNETIC_FIELD_SENSOR_TYPE, PROXIMITY_SENSOR_TYPE, ROTATION_VECTOR_SENSOR_TYPE, HEART_RATE_SENSOR_TYPE)
}