name: CI Debug artifact

on:
  push:
    tags:
      - '*d'

jobs:
  Build_debug_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build debug apk
        run: ./gradlew clean assembleDebug --stacktrace

      - name: Rename built artifact
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/SensorsManager_debug_${{ github.run_number }}.apk

      - name: Export debug apk
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: app/build/outputs/apk/debug/SensorsManager_debug_${{ github.run_number }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
